### PR TITLE
Persist charms in LocalStorage

### PR DESCRIPTION
**Pull request by seefeldb**
- Introduces storage on top of cells, syncing across tabs
- Adds a lot of causality where ids are being generated, but probably not yet catching all cases
- Switch creation of all charms to be persistent
- Tons and tons of bug fixes around race conditions, etc., that were previously not triggered

### CODE REVIEW

**Comment by anotherjesse** [comment]
so far it is looking pretty good.

The only (potential) issues I'm seeing are:

1. if you `localStorage.clear()` then refresh while the has a charm (like [this](http://localhost:5173/charm/%7B%22/%22:%22baedreig7o72rl5fy5467r2kdicouitvb5qejunsrhd3msq3qv2p5tfq4bi%22%7D) - it leaves you with an empty "pinned" list

image

If you change your path to `/` (removing the charm) - then refresh - it then it **white screens of death** (nothing rendered)

but if you `localStorage.clear()` again and refresh again, you see all the pinned items:

image

2. if you `localStorage.clear()` while there are multiple tabs open (one navigated to , infinite loop occurs in the non-cleared tab:

image

detailed steps:

- open localhost:5173 in two windows with console visible
- in one, click the recipe "explore imagery prompts", in the second go to charm "counters"
- in the "counters" console, type `localStorage.clear()` then hit refresh

at this point both windows infinite loop

3. infinite loop with 2 tabs without using `localStorage.clear()`

- open localhost:5173 in ONLY one tab
- `localStorage.clear()` away any previous stuff (perhaps navigating to /clear should do this for you - so we can just open localhost:5173/clear and we know we have a clean state)
- refresh so that we aren't in a weird state
- in a second tab open localhost:5173
- browse to two diferent recipes/gems (using "find places" and "luftbnb" is usually pretty good for triggering)
- click refresh every once in a while in one or the other tab
- within ~30 seconds I trigger both tabs infinite send/receive

Export-1729967950205

**Comment by anotherjesse** [comment]
clicking "book" on a luftbnb breaks the window manager:

```
window-manager.ts:343 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'icon')
    at window-manager.ts:343:45
    at RepeatDirective._getValuesAndKeys (repeat.ts:57:23)
    at RepeatDirective.update (repeat.ts:93:53)
    at RepeatDirective._$resolve (directive.ts:135:17)
    at resolveDirective (lit-html.ts:1168:24)
    at _ChildPart._$setValue (lit-html.ts:1446:13)
    at TemplateInstance._update (lit-html.ts:1276:16)
    at _ChildPart._commitTemplateResult (lit-html.ts:1630:51)
    at _ChildPart._$setValue (lit-html.ts:1469:12)
    at render (lit-html.ts:2269:8)
    ```

**Comment by anotherjesse** [comment]
I wasn't expecting to see all these sends into localstorage because nothing is connected to `partial`

```
  const { result, pending } = llm(buildPrompt({prompt}))
```

image

I'm guessing llm sending partial will trigger this persisting even if no-one cares?

**Comment by anotherjesse** [comment]
Single tab - sometimes luftbnb doesn't render results (I think this is the ifElse bug not switching which is shown after complete)

Steps:

1. in a single tab, create a luftbnb search for a NEW location (break cache!)
2. even when you see the console calm down/completed you won't see results
3. copy the url, open a new tab, paste url

you will see the results in the new tab, but the old tab shows "searching..."

**Comment by anotherjesse** [comment]
I'm not sure how this happens, but sometimes when you are browsing with two tabs open to it, you can end up with clicking in one location navigates both to the different charm.

I can't get it consistently to happen

**Comment by anotherjesse** [comment]
would it be possible to notice if we were doing hundreds of updates per second and say "ABORT, BROKEN, ALERT"

**Comment by seefeldb** [comment]
thanks for all the comments
- added a timeout for loading from storage, which will trigger when (a) opening a charm that doesn't exist or (b) localstorage.clear() removed things from storage that the system expected to exist
- don't open a charm that failed to load
- made windowmanager more robust against empty charms, since those can now exist due to aforementioned timeouts in other cases

**Comment by seefeldb** [comment]
> I wasn't expecting to see all these sends into localstorage because nothing is connected to `partial`
> I'm guessing llm sending partial will trigger this persisting even if no-one cares?

That's right, it's currently tracking all cells written to.

We should optimize this in a future PR.

Maybe it's sufficient to ignore cells that don't have any subscribers, but I'm not 100% sure: Subscribers change depending on what a module actually read, and so if module B isn't yet ready to read from module A because it's waiting for some other data, then module A's output would be not be saved. But then again, that's probably fine.

Taking this a step further, we might want to only compute things that are rendered on screen. Here we'd more systematically note that `pending` isn't used by anything and ignore it.

**Comment by seefeldb** [comment]
[logging debugging of infinite loop]
- i can trigger an infinite loop with the iframe example immediately
- ah, it keeps issuing llm requests as well. they are cached, so it goes fast.

**Comment by seefeldb** [comment]
still causing infinite loops when fetching is involved, but committing now with default to "memory", which exercises the storage infrastructure but should be a no-op most of the time.

**Pull request merged**
