### PR TITLE
linkheap Prototype

### PR DESCRIPTION
**Pull request by bfollington**
Link clipping playground. Save links to collections, scrape the markup and do some basic LLM analysis.

Then, generate views of the various collections!

### CODE REVIEW

**Comment by anotherjesse** [comment]
I did a quick look before bed 🔥 

will give a proper review tomorrow - and kick the tires

**Comment by anotherjesse** [comment]
not sure if I'm holding it wrong but I have an anthropic key set...

```
% rm links.db 
% npm run start

> @commontools/linkheap@0.0.1 start
> deno run --allow-net --allow-read --allow-write --allow-env --allow-run main.ts

Welcome to the Link Saver CLI!
Available commands:
  save <URL> [collection1 collection2 ...] [--comment <COMMENT>]
  list [<COLLECTION>]
  view <COLLECTION> [<COMMENT>]
  imagine <COLLECTION> [<COMMENT>]
  refresh <URL>
  exit
save https://example.com/ foo
Saved link: https://example.com/
Collections: foo
Navigating to https://example.com/
Loaded!
Error analyzing link: system: text content blocks must be non-empty
```

**Comment by anotherjesse** [comment]
I'm happy to send in a PR that:

- makes it so errors propagate up 
- make `npm run start` (or have a helper that can be used to validate) fail if anthropic or puppeter isn't ready

both of those make having a chrome (or other client) connected to it better...

we can address these in a latter commit - this isn't a "reject" 

---

I would click "squash and merge" if I could validate it works.  (I haven't looked at what `text content blocks must be non-empty` might mean)

**Comment by bfollington** [comment]
@anotherjesse 

> Error analyzing link: system: text content blocks must be non-empty

This was a change in the latest version of the Anthropic SDK, I wasn't using fixed package versions in Deno before so it didn't happen to me. Versioned all the packages and updated the system prompt to have some content (the source of the error on newer versions).

I'm happy for you to push to this branch OR I can land this PR if you want to open a follow-up with your changes?

**Comment by anotherjesse** [comment]
Land it.

I’ll try it out tomorrow

**Review by anotherjesse — APPROVED** [review]
Lgtm

I have some tweaks I’ll send as a pr

**Pull request merged**
