### PR TITLE
jsx support

### PR DESCRIPTION
**Pull request by anotherjesse**
- generate a vnode vdom using jsx
- common-html render updates to support raw render of vdom
- update recipes to typescript

### CODE REVIEW

**Comment by anotherjesse** [comment]
I will document the jsx.ts file better (before or after merge)

**Comment by anotherjesse** [comment]
@gordonbrander should we remove the html` pattern / code paths related to it?

**Comment by seefeldb** [comment]
> @gordonbrander should we remove the html` pattern / code paths related to it?

If not in the way, I'd keep them so we can later experiment with these other styles. WDYT?

**Comment by anotherjesse** [comment]
👍 Its ok with me.  The complexity to handle both in render/renderNode is quite small.  I'm always looking for ways to delete code in general ... code = liability but also code = ability

**Comment by anotherjesse** [comment]
fyi @seefeldb - naive approach to supporting subrecipes:

- something `isRecipe` if it has a key $UI and the value of the key is a view or vnode
- if the replacement isRecipe, replacement = replacement[$UI]

issues:

- does replacement = replacement[$UI] break updates if the next thing doesn't return a recipe
- better way of checking for recipeness


```patch
diff --git a/typescript/packages/common-html/src/render.ts b/typescript/packages/common-html/src/render.ts
index 592c584..18fd18d 100644
--- a/typescript/packages/common-html/src/render.ts
+++ b/typescript/packages/common-html/src/render.ts
@@ -33,6 +33,8 @@ export const render = (parent: HTMLElement, view: View | VNode): Cancel => {
   return cancel;
 };
 
+const isRecipe = (node: any) => node && (isView(node['$UI']) || isVNode(node['$UI']));
+
 export default render;
 
 const renderNode = (
@@ -84,6 +86,7 @@ const bindChildren = (
       let endAnchor: ChildNode | undefined = undefined;
       element.append(anchor);
       const replace = (replacement: any) => {
+        console.log('replace', replacement, isRecipe(replacement))
         if (isReactive(replacement)) {
           const cancel = effect(replacement, replace);
           addCancel(cancel);
@@ -111,7 +114,10 @@ const bindChildren = (
             replace(item);
           }
           anchor = originalAnchor;
-        } else if (isView(replacement) || isVNode(replacement)) {
+        } else if (isRecipe(replacement) || isView(replacement) || isVNode(replacement)) {
+          if (isRecipe(replacement)) {
+            replacement = replacement['$UI']
+          }
           const [childElement, cancel] = isView(replacement) ? renderNode(
             replacement.template,
             replacement.context
```

**Comment by seefeldb** [comment]
> fyi @seefeldb - naive approach to supporting subrecipes:
> 
> * something `isRecipe` if it has a key $UI and the value of the key is a view or vnode
> * if the replacement isRecipe, replacement = replacement[$UI]
> 
> issues:
> 
> * does replacement = replacement[$UI] break updates if the next thing doesn't return a recipe
> * better way of checking for recipeness
> 
> ```diff
> diff --git a/typescript/packages/common-html/src/render.ts b/typescript/packages/common-html/src/render.ts
> index 592c584..18fd18d 100644
> --- a/typescript/packages/common-html/src/render.ts
> +++ b/typescript/packages/common-html/src/render.ts
> @@ -33,6 +33,8 @@ export const render = (parent: HTMLElement, view: View | VNode): Cancel => {
>    return cancel;
>  };
>  
> +const isRecipe = (node: any) => node && (isView(node['$UI']) || isVNode(node['$UI']));
> ```

There is already a `isRecipe` in builder that checks for what `recipe` generates. This is more like a charm-with-UI, but I think we're trying to reserve charm for the user-level concept, not e.g. the mapping cells (though the code still does so in a few places). Maybe `hasUI` or `hasUIprop`?

The other problem though is that $UI could be a cell itself, and so the second part will fail. I'm not sure it's worth checking here though: Adding such a cell to the vdom shows the intent of how $UI should be interpreted, so I'd just check for the presence of it, then register another `effect` on the value itself, to catch both the cell and non-cell case.

(Also check for `typeof node === "object" && node !== null &&` instead of `node &&`, so you don't get errors when it's undefined or a literal)

> ```ts
> +
>  export default render;
>  
>  const renderNode = (
> @@ -84,6 +86,7 @@ const bindChildren = (
>        let endAnchor: ChildNode | undefined = undefined;
>        element.append(anchor);
>        const replace = (replacement: any) => {
> +        console.log('replace', replacement, isRecipe(replacement))
>          if (isReactive(replacement)) {
>            const cancel = effect(replacement, replace);
>            addCancel(cancel);
> @@ -111,7 +114,10 @@ const bindChildren = (
>              replace(item);
>            }
>            anchor = originalAnchor;
> -        } else if (isView(replacement) || isVNode(replacement)) {
> +        } else if (isRecipe(replacement) || isView(replacement) || isVNode(replacement)) {
> +          if (isRecipe(replacement)) {
> +            replacement = replacement['$UI']
> +          }
> ```

Here is where I'd do a separate if statement and then just say `addCancel(effect(replacement["$UI"], replace)`

> ```ts
>            const [childElement, cancel] = isView(replacement) ? renderNode(
>              replacement.template,
>              replacement.context
> ```

**Pull request merged**
